const mockTeamCompetitions = [
  {
    id: 'cmp-2025-metropolitana',
    name: 'Copa Metropolitana',
    season: '2025',
    categories: [
      { id: 'cat-serie-a', name: 'Série A' },
      { id: 'cat-sub-20', name: 'Sub-20' },
    ],
  },
  {
    id: 'cmp-2025-cidade',
    name: 'Taça Cidade',
    season: '2025',
    categories: [
      { id: 'cat-livre', name: 'Livre' },
      { id: 'cat-feminino', name: 'Feminino' },
    ],
  },
]

const mockTeams = [
  {
    id: 101,
    equipe: 'Bairro Azul',
    categoria: 'cat-serie-a',
    V: 6,
    D: 2,
    E: 1,
    GP: 18,
    GC: 9,
    SG: 9,
    part: 9,
    PTS: 19,
    class: 2,
    porcentagem: 70,
    legenda: 'Equipe com boa defesa e ataques rápidos pelas laterais.',
    wo: 0,
    qtdAmarelo: 8,
    qtdVermelho: 1,
    ptAmarelo: 8,
    ptVermelho: 3,
    pontuacaoCartoes: 11,
    classificacao_disciplinar: 3,
    id_competicao: 'cmp-2025-metropolitana',
    chave: 'A',
    pp: 2,
    pg: 6,
    representante1: 'Carlos Mendes',
    representante2: 'Fernanda Lopes',
    email_rp1: 'carlos.mendes@bairroazul.com',
    email_rp2: 'fernanda.lopes@bairroazul.com',
    fone_rp1: '(11) 99999-1200',
    fone_rp2: '(11) 98888-4433',
    tecnico: 'Ricardo Alves',
    auxiliartecnico: 'Marina Rocha',
    rebaixamento: 'Não',
  },
  {
    id: 202,
    equipe: 'União Estrela',
    categoria: 'cat-serie-a',
    V: 4,
    D: 3,
    E: 2,
    GP: 14,
    GC: 12,
    SG: 2,
    part: 9,
    PTS: 14,
    class: 5,
    porcentagem: 52,
    legenda: 'Time em reconstrução com foco na base.',
    wo: 0,
    qtdAmarelo: 10,
    qtdVermelho: 0,
    ptAmarelo: 10,
    ptVermelho: 0,
    pontuacaoCartoes: 10,
    classificacao_disciplinar: 4,
    id_competicao: 'cmp-2025-metropolitana',
    chave: 'B',
    pp: 3,
    pg: 4,
    representante1: 'Patrícia Gomes',
    representante2: 'João Viana',
    email_rp1: 'patricia.gomes@uniaoestrela.com',
    email_rp2: 'joao.viana@uniaoestrela.com',
    fone_rp1: '(11) 97777-2211',
    fone_rp2: '(11) 96666-3344',
    tecnico: 'Henrique Costa',
    auxiliartecnico: 'Luiz Paulo',
    rebaixamento: 'Não',
  },
  {
    id: 303,
    equipe: 'Aurora FC',
    categoria: 'cat-feminino',
    V: 7,
    D: 1,
    E: 1,
    GP: 22,
    GC: 7,
    SG: 15,
    part: 9,
    PTS: 22,
    class: 1,
    porcentagem: 81,
    legenda: 'Campanha dominante com ataque poderoso.',
    wo: 0,
    qtdAmarelo: 5,
    qtdVermelho: 0,
    ptAmarelo: 5,
    ptVermelho: 0,
    pontuacaoCartoes: 5,
    classificacao_disciplinar: 1,
    id_competicao: 'cmp-2025-cidade',
    chave: 'A',
    pp: 1,
    pg: 7,
    representante1: 'Aline Souza',
    representante2: 'Camila Nunes',
    email_rp1: 'aline.souza@aurorafc.com',
    email_rp2: 'camila.nunes@aurorafc.com',
    fone_rp1: '(21) 98888-7744',
    fone_rp2: '(21) 97777-8855',
    tecnico: 'Marina Duarte',
    auxiliartecnico: 'Renata Cruz',
    rebaixamento: 'Não',
  },
]

const cloneTeams = (teams) => teams.map((team) => ({ ...team }))
const cloneCompetitions = (competitions) =>
  competitions.map((competition) => ({
    ...competition,
    categories: competition.categories.map((category) => ({ ...category })),
  }))

export const fetchTeamSetup = () =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        competitions: cloneCompetitions(mockTeamCompetitions),
        teams: cloneTeams(mockTeams),
      })
    }, 300)
  })

export default fetchTeamSetup
