export const MENU_ALLOWED_OPTIONS = [
  { menu: 'Notícias', alias: 'noticias' },
  { menu: 'Patrocinadores', alias: 'patrocinadores' },
  { menu: 'Upload Súmula', alias: 'upload_sumula' },
  { menu: 'RGC', alias: 'pdf_rgc' },
  { menu: 'CDE', alias: 'pdf_cde' },
  { menu: 'Resultado julgamento', alias: 'pdf_resultado_julgamento' },
  { menu: 'Outros anexos', alias: 'pdf_outros_anexos' },
  { menu: 'Escudo de equipe', alias: 'escudo_equipe' },
  { menu: 'Jogadores', alias: 'jogadores' },
  { menu: 'Equipes', alias: 'equipes' },
  { menu: 'Categorias', alias: 'categorias' },
  { menu: 'Súmula', alias: 'sumula' },
  { menu: 'Jogos', alias: 'jogos' },
  { menu: 'Usuários', alias: 'usuarios' },
  { menu: 'Competição', alias: 'competicao' },
  { menu: 'Súmula Campo', alias: 'sumula_campo' },
  { menu: 'Súmula Futsal', alias: 'sumula_futsal' },
  { menu: 'Rodada da Semana', alias: 'rodada_da_semana' },
  { menu: 'Tabela de jogos completo', alias: 'tabela_jogos_completo' },
  { menu: 'Julgamento', alias: 'relatorios_julgamento' },
  { menu: 'Artilheiros', alias: 'artilheiros' },
  { menu: 'Histórico', alias: 'historico' },
]

export const MENU_ALIAS_BY_ROUTE = {
  'painel/noticiascompeticao': 'noticias',
  'painel/patrocinadores': 'patrocinadores',
  'painel/viewuploadsumula': 'upload_sumula',
  'painel/competicoes/pdf/rgc': 'pdf_rgc',
  'painel/competicoes/pdf/cde': 'pdf_cde',
  'painel/competicoes/pdf/resultado': 'pdf_resultado_julgamento',
  'painel/competicoes/pdf/outros-anexos': 'pdf_outros_anexos',
  'painel/equipes/reports/logo': 'escudo_equipe',
  'painel/criarjogadores': 'jogadores',
  'painel/criarequipes': 'equipes',
  'painel/categorias': 'categorias',
  'sumula/selecao': 'sumula',
  'painel/viewjogos': 'jogos',
  'user/admin': 'usuarios',
  'gerenciador/competicao/admin': 'competicao',
  'painel/sumulacampo': 'sumula_campo',
  'painel/sumulafutsal': 'sumula_futsal',
  'painel/tblsemana': 'rodada_da_semana',
  'painel/tabela_jogos_completo': 'tabela_jogos_completo',
  'painel/julgamento': 'relatorios_julgamento',
  'painel/artilheiros-geral': 'artilheiros',
  'historico/admin': 'historico',
}
